LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := vendor.qti.hardware.display.config-V7-ndk.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/vendor/lib64
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_CHECK_ELF_FILES := false
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := android.hardware.common-V2-ndk.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/vendor/lib64
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_CHECK_ELF_FILES := false
include $(BUILD_PREBUILT)
